enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 2


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "both"
build-mode = "both"
version = "20.21.37"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
included-patches = "'Hide Shorts dimming' 'Hide shortcuts'"
patcher-args = """\
-e 'Custom branding name for YouTube' \
-OappName=YouTube \
-e 'Settings for YouTube' \
-OrvxSettingsLabel='Revanced Settings' \
-OsettingsSummaries=true \
-OinsertPosition=@string/about_key \
-e 'Theme' \
-OdarkThemeBackgroundColor=@android:color/black \
-e 'GmsCore support' \
-OpackageNameYouTube=com.google.android.youtube \
-OpackageNameYouTubeMusic=com.google.android.apps.youtube.music \
"""

[YouTube-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"
build-mode = "both"
version = "8.30.54"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
included-patches = "'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = """\
-e 'Custom branding name for YouTube Music' \
-OappNameNotification='YouTube Music' \
-OappNameLauncher='YT Music' \
-e 'Settings for YouTube Music' \
-OrvxSettingsLabel='Revanced Settings' \
-OsettingsSummaries=true \
-OinsertPosition=settings_header_about_youtube_music \
-e 'GmsCore support' \
-OpackageNameYouTube=com.google.android.youtube \
-OpackageNameYouTubeMusic=com.google.android.apps.youtube.music \
"""

[GooglePhotos]
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Reddit]
# apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
build-mode = "apk"
arch = "universal"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
patcher-args = """\
-e 'Settings for Reddit' -OrvxSettingsLabel='Revanced Settings' \
"""

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
